/**
 * Generated by orval — do not edit manually.
 */
import type { DataResponseNotificationListResponse } from '../models/dataResponseNotificationListResponse'

import type { DataResponseVoid } from '../models/dataResponseVoid'

import type { GetNotificationsParams } from '../models/getNotificationsParams'

import { customFetch } from '../../customFetch.api'

export const getReadNotificationUrl = (notificationId: number) => {
  return `/api/notifications/${notificationId}/read`
}

/**
 * 본인이 받은 알림 하나를 읽음 상태로 변경합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 알림 단건 읽음 처리
 */
export const readNotification = async (
  notificationId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getReadNotificationUrl(notificationId), {
    ...options,
    method: 'PATCH',
  })
}

export const getReadAllNotificationsUrl = () => {
  return `/api/notifications/read-all`
}

/**
 * 본인이 받은 안 읽은 알림을 모두 읽음 상태로 변경합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 알림 전체 읽음 처리
 */
export const readAllNotifications = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getReadAllNotificationsUrl(), {
    ...options,
    method: 'PATCH',
  })
}

export const getGetNotificationsUrl = (params?: GetNotificationsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/notifications?${stringifiedParams}`
    : `/api/notifications`
}

/**
 * 내가 받은 알림을 최신순으로 페이지네이션 조회합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 알림 목록 조회
 */
export const getNotifications = async (
  params?: GetNotificationsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseNotificationListResponse> => {
  return customFetch<DataResponseNotificationListResponse>(getGetNotificationsUrl(params), {
    ...options,
    method: 'GET',
  })
}
