/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */
import type { DataResponseUserBookStatusResponse } from '../models/dataResponseUserBookStatusResponse'

import type { UpdateUserBookStatusRequest } from '../models/updateUserBookStatusRequest'

import { customFetch } from '../../customFetch.api'

export const getUpdateBookStatusUrl = () => {
  return `/api/users/me/book-status`
}

/**
 * 로그인한 사용자의 특정 도서에 대한 읽기상태와 현재 페이지를 설정합니다. 기존 상태가 없으면 새로 생성합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 읽기상태/현재페이지 설정
 */
export const updateBookStatus = async (
  updateUserBookStatusRequest: UpdateUserBookStatusRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseUserBookStatusResponse> => {
  return customFetch<DataResponseUserBookStatusResponse>(getUpdateBookStatusUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserBookStatusRequest),
  })
}
