import { defineConfig } from 'orval'

export default defineConfig({
  pallang: {
    input: {
      target: 'https://api-dev.pallang.co.kr/v3/api-docs',
      override: {
        transformer: './orval.transformer.ts',
      },
    },
    output: {
      mode: 'tags-split',
      client: 'fetch',
      target: 'app/_global/_apis/_generated',
      schemas: 'app/_global/_apis/_generated/models',
      formatter: 'prettier',
      indexFiles: false,
      override: {
        // 버전·orval 버전 줄 제거 — 스펙/도구 버전이 바뀔 때마다 전 파일 diff가 생기는 것 방지
        header: () => ['Generated by orval — do not edit manually.'],
        mutator: {
          path: 'app/_global/_apis/customFetch.api.ts',
          name: 'customFetch',
        },
        fetch: {
          includeHttpResponseReturnType: false,
        },
      },
    },
  },
})
