/**
 * Generated by orval — do not edit manually.
 */
import type { DataResponseVoid } from '../models/dataResponseVoid'

import type { RegisterDeviceTokenRequest } from '../models/registerDeviceTokenRequest'

import type { RemoveDeviceTokenParams } from '../models/removeDeviceTokenParams'

import { customFetch } from '../../customFetch.api'

export const getRegisterDeviceTokenUrl = () => {
  return `/api/notifications/device-tokens`
}

/**
 * FCM 디바이스 토큰을 등록합니다. 이미 등록된 토큰이면(재설치/재로그인 등) 소유자를 현재 로그인 사용자로 갱신합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 디바이스 토큰 등록/갱신
 */
export const registerDeviceToken = async (
  registerDeviceTokenRequest: RegisterDeviceTokenRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getRegisterDeviceTokenUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerDeviceTokenRequest),
  })
}

export const getRemoveDeviceTokenUrl = (params: RemoveDeviceTokenParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/notifications/device-tokens?${stringifiedParams}`
    : `/api/notifications/device-tokens`
}

/**
 * 로그아웃 등으로 더 이상 유효하지 않은 디바이스 토큰을 삭제합니다. 본인 소유가 아니거나 존재하지 않는 토큰이어도 멱등하게 200을 반환합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 디바이스 토큰 삭제
 */
export const removeDeviceToken = async (
  params: RemoveDeviceTokenParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getRemoveDeviceTokenUrl(params), {
    ...options,
    method: 'DELETE',
  })
}
