/**
 * Generated by orval — do not edit manually.
 */

export interface AppleLoginRequest {
  /** @minLength 1 */
  identityToken: string
  /** 회원탈퇴 시 애플 연동 해제(revoke)용 refresh token 확보에 사용한다. 없어도 로그인 자체는 진행된다. */
  authorizationCode?: string
  /** 애플이 최초 로그인 시에만 내려주는 이름. 이후 로그인엔 null일 수 있다. */
  givenName?: string
  /** 애플이 최초 로그인 시에만 내려주는 성. 이후 로그인엔 null일 수 있다. */
  familyName?: string
}
