/**
 * Generated by orval — do not edit manually.
 */

export interface BlockedUserResponse {
  userId: number
  nickname: string
  /** @nullable */
  profileImageUrl?: string | null
  blockedAt: string
}
