/**
 * Generated by orval — do not edit manually.
 */
import type { BlockedUserResponse } from './blockedUserResponse'
import type { PageInfo } from './pageInfo'

export interface BlockedUserListResponse {
  users: BlockedUserResponse[]
  pageInfo: PageInfo
}
