/**
 * Generated by orval — do not edit manually.
 */

/**
 * @nullable
 */
export type BookDetailResponseMyStatus =
  (typeof BookDetailResponseMyStatus)[keyof typeof BookDetailResponseMyStatus] | null

export const BookDetailResponseMyStatus = {
  READING: 'READING',
  PLANNED: 'PLANNED',
  FINISHED: 'FINISHED',
} as const
