/**
 * Generated by orval — do not edit manually.
 */

export interface BookActivityResponse {
  bookId?: number
  title?: string
  author?: string
  coverImageUrl?: string
  passageCount?: number
  opinionCount?: number
}
