/**
 * Generated by orval — do not edit manually.
 */
import type { BookActivityResponse } from './bookActivityResponse'
import type { CarouselPageInfo } from './carouselPageInfo'

export interface BookCarouselListResponse {
  books: BookActivityResponse[]
  pageInfo: CarouselPageInfo
}
