/**
 * Generated by orval — do not edit manually.
 */
import type { BookResponseSource } from './bookResponseSource'

export interface BookResponse {
  bookId: number
  title: string
  author: string
  publisher: string
  pageCount: number
  /** @nullable */
  isbn?: string | null
  /** @nullable */
  coverImageUrl?: string | null
  source: BookResponseSource
}
