/**
 * Generated by orval — do not edit manually.
 */
import type { BookDetailResponseMyStatus } from './bookDetailResponseMyStatus'

export interface BookDetailResponse {
  bookId: number
  title: string
  author: string
  publisher: string
  pageCount: number
  /** @nullable */
  coverImageUrl?: string | null
  passageCount: number
  opinionCount: number
  /** @nullable */
  myStatus?: BookDetailResponseMyStatus
  /** @nullable */
  myCurrentPage?: number | null
}
