/**
 * Generated by orval — do not edit manually.
 */
import type { BookActivityResponse } from './bookActivityResponse'
import type { PageInfo } from './pageInfo'

export interface BookActivityListResponse {
  books?: BookActivityResponse[]
  pageInfo?: PageInfo
}
