/**
 * Generated by orval — do not edit manually.
 */

/**
 * bookId와 마찬가지로 미등록 도서는 null이다.
 * @nullable
 */
export type BookSearchResponseSource =
  (typeof BookSearchResponseSource)[keyof typeof BookSearchResponseSource] | null

export const BookSearchResponseSource = {
  API: 'API',
  MANUAL: 'MANUAL',
} as const
