/**
 * Generated by orval — do not edit manually.
 */
import type { BookResponseSource } from './bookResponseSource'

export interface BookResponse {
  bookId?: number
  title?: string
  author?: string
  publisher?: string
  pageCount?: number
  isbn?: string
  coverImageUrl?: string
  source?: BookResponseSource
}
