/**
 * Generated by orval — do not edit manually.
 */
import type { BookSearchResponseSource } from './bookSearchResponseSource'

export interface BookSearchResponse {
  bookId: number
  title: string
  author: string
  publisher: string
  pageCount: number
  /** @nullable */
  isbn?: string | null
  /** @nullable */
  coverImageUrl?: string | null
  source: BookSearchResponseSource
  passageCount: number
  opinionCount: number
}
