/**
 * Generated by orval — do not edit manually.
 */

export interface BookActivityResponse {
  bookId: number
  title: string
  author: string
  publisher: string
  /** @nullable */
  coverImageUrl?: string | null
  passageCount: number
  opinionCount: number
}
