/**
 * Generated by orval — do not edit manually.
 */
import type { BookSearchResponse } from './bookSearchResponse'
import type { PageInfo } from './pageInfo'

export interface BookSearchListResponse {
  books: BookSearchResponse[]
  pageInfo: PageInfo
}
