/**
 * Generated by orval — do not edit manually.
 */

export type BookSearchResponseSource =
  (typeof BookSearchResponseSource)[keyof typeof BookSearchResponseSource]

export const BookSearchResponseSource = {
  API: 'API',
  MANUAL: 'MANUAL',
} as const
