/**
 * Generated by orval — do not edit manually.
 */

export type BookResponseSource = (typeof BookResponseSource)[keyof typeof BookResponseSource]

export const BookResponseSource = {
  API: 'API',
  MANUAL: 'MANUAL',
} as const
