/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */
import type { BookResponseSource } from './bookResponseSource'

export interface BookResponse {
  bookId?: number
  title?: string
  author?: string
  publisher?: string
  pageCount?: number
  isbn?: string
  coverImageUrl?: string
  source?: BookResponseSource
}
