/**
 * Generated by orval — do not edit manually.
 */
import type { BookResponse } from './bookResponse'
import type { PageInfo } from './pageInfo'

export interface BookListResponse {
  books?: BookResponse[]
  pageInfo?: PageInfo
}
