/**
 * Generated by orval — do not edit manually.
 */
import type { CommentResponse } from './commentResponse'
import type { PageInfo } from './pageInfo'

export interface CommentListResponse {
  comments?: CommentResponse[]
  pageInfo?: PageInfo
}
