/**
 * Generated by orval — do not edit manually.
 */

export interface CommentResponse {
  commentId?: number
  userId?: number
  nickname?: string
  profileImageUrl?: string
  content?: string
  isDeleted?: boolean
  createdAt?: string
  updatedAt?: string
}
