/**
 * Generated by orval — do not edit manually.
 */

export interface CommentResponse {
  commentId: number
  userId: number
  nickname: string
  /** @nullable */
  profileImageUrl?: string | null
  content: string
  isDeleted: boolean
  createdAt: string
  updatedAt: string
}
