/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */

export interface CreateBookRequest {
  /** @minLength 1 */
  title: string
  /** @minLength 1 */
  author: string
  /** @minLength 1 */
  publisher: string
  pageCount?: number
  isbn?: string
  coverImageUrl?: string
}
