/**
 * Generated by orval — do not edit manually.
 */
import type { CreateBookRequest } from './createBookRequest'

export type CreateBookBody = {
  book: CreateBookRequest
  /** 책 표지 이미지 파일 (jpeg/png, 선택) */
  coverImage?: Blob
}
