/**
 * Generated by orval — do not edit manually.
 */
import type { CreateReportRequestReason } from './createReportRequestReason'

export interface CreateReportRequest {
  reason: CreateReportRequestReason
  /**
   * 기타 사유 선택 시 필수
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  detail?: string | null
}
