/**
 * Generated by orval — do not edit manually.
 */

export interface CreateCommentRequest {
  /**
   * 답글로 남길 경우 원댓글 ID. 원댓글이면 null입니다.
   * @nullable
   */
  parentCommentId?: number | null
  /**
   * @minLength 0
   * @maxLength 500
   */
  content: string
}
