/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */

export type CreateOcrResultBody = {
  /** 텍스트를 추출할 이미지 파일 (지원 포맷: JPEG, PNG) */
  image: Blob
}
