/**
 * Generated by orval — do not edit manually.
 */

export interface CreateBookRequest {
  /** @minLength 1 */
  title: string
  /** @minLength 1 */
  author: string
  /** @minLength 1 */
  publisher: string
  pageCount?: number
  isbn?: string
}
