/**
 * Generated by orval — do not edit manually.
 */
import type { DecorationRequest } from './decorationRequest'

export interface CreateOpinionRequest {
  bookId: number
  pageNumber?: number
  /**
   * @minLength 0
   * @maxLength 150
   */
  quotedText: string
  isSpoiler?: boolean
  /**
   * 병합할 기존 대목 ID. 없으면 새 대목을 생성합니다.
   * @nullable
   */
  passageId?: number | null
  /**
   * @minLength 0
   * @maxLength 500
   */
  content: string
  /** @minItems 1 */
  decorations: DecorationRequest[]
}
