/**
 * Generated by orval — do not edit manually.
 */

export interface CreateGroupRequest {
  /**
   * @minLength 0
   * @maxLength 15
   */
  name: string
  bookId: number
  /**
   * @minimum 2
   * @maximum 10
   */
  capacity?: number
  startDate: string
  endDate: string
}
