/**
 * Generated by orval — do not edit manually.
 */

export type CreateReportRequestReason =
  (typeof CreateReportRequestReason)[keyof typeof CreateReportRequestReason]

export const CreateReportRequestReason = {
  SPAM: 'SPAM',
  HATE: 'HATE',
  ABUSE: 'ABUSE',
  COPYRIGHT: 'COPYRIGHT',
  ETC: 'ETC',
} as const
