/**
 * Generated by orval — do not edit manually.
 */
import type { OnboardingCompleteResponse } from './onboardingCompleteResponse'

export interface DataResponseOnboardingCompleteResponse {
  data?: OnboardingCompleteResponse
}
