/**
 * Generated by orval — do not edit manually.
 */
import type { BookSearchListResponse } from './bookSearchListResponse'

export interface DataResponseBookSearchListResponse {
  data?: BookSearchListResponse
}
