/**
 * Generated by orval — do not edit manually.
 */
import type { BookActivityListResponse } from './bookActivityListResponse'

export interface DataResponseBookActivityListResponse {
  data?: BookActivityListResponse
}
