/**
 * Generated by orval — do not edit manually.
 */
import type { BlockedUserListResponse } from './blockedUserListResponse'

export interface DataResponseBlockedUserListResponse {
  data?: BlockedUserListResponse
}
