/**
 * Generated by orval — do not edit manually.
 */
import type { TermsAgreementResponse } from './termsAgreementResponse'

export interface DataResponseTermsAgreementResponse {
  data?: TermsAgreementResponse
}
