/**
 * Generated by orval — do not edit manually.
 */
import type { RootCommentListResponse } from './rootCommentListResponse'

export interface DataResponseRootCommentListResponse {
  data?: RootCommentListResponse
}
