/**
 * Generated by orval — do not edit manually.
 */
import type { NotificationListResponse } from './notificationListResponse'

export interface DataResponseNotificationListResponse {
  data?: NotificationListResponse
}
