/**
 * Generated by orval — do not edit manually.
 */
import type { GroupInviteLinkResponse } from './groupInviteLinkResponse'

export interface DataResponseGroupInviteLinkResponse {
  data?: GroupInviteLinkResponse
}
