/**
 * Generated by orval — do not edit manually.
 */
import type { ExternalBookListResponse } from './externalBookListResponse'

export interface DataResponseExternalBookListResponse {
  data?: ExternalBookListResponse
}
