/**
 * Generated by orval — do not edit manually.
 */
import type { BookCarouselListResponse } from './bookCarouselListResponse'

export interface DataResponseBookCarouselListResponse {
  data?: BookCarouselListResponse
}
