/**
 * Generated by orval — do not edit manually.
 */
import type { CommentListResponse } from './commentListResponse'

export interface DataResponseCommentListResponse {
  data?: CommentListResponse
}
