/**
 * Generated by orval — do not edit manually.
 */
import type { OpinionLikeResponse } from './opinionLikeResponse'

export interface DataResponseOpinionLikeResponse {
  data?: OpinionLikeResponse
}
