/**
 * Generated by orval — do not edit manually.
 */
import type { OpinionDetailResponse } from './opinionDetailResponse'

export interface DataResponseOpinionDetailResponse {
  data?: OpinionDetailResponse
}
