/**
 * Generated by orval — do not edit manually.
 */
import type { UserBookStatusResponse } from './userBookStatusResponse'

export interface DataResponseUserBookStatusResponse {
  data?: UserBookStatusResponse
}
