/**
 * Generated by orval — do not edit manually.
 */
import type { FilterBooksResponse } from './filterBooksResponse'

export interface DataResponseFilterBooksResponse {
  data?: FilterBooksResponse
}
