/**
 * Generated by orval — do not edit manually.
 */
import type { GroupDetailResponse } from './groupDetailResponse'

export interface DataResponseGroupDetailResponse {
  data?: GroupDetailResponse
}
