/**
 * Generated by orval — do not edit manually.
 */
import type { GroupMemberListResponse } from './groupMemberListResponse'

export interface DataResponseGroupMemberListResponse {
  data?: GroupMemberListResponse
}
