/**
 * Generated by orval — do not edit manually.
 */
import type { GroupInvitationPreviewResponse } from './groupInvitationPreviewResponse'

export interface DataResponseGroupInvitationPreviewResponse {
  data?: GroupInvitationPreviewResponse
}
