/**
 * Generated by orval — do not edit manually.
 */
import type { MyPassageListResponse } from './myPassageListResponse'

export interface DataResponseMyPassageListResponse {
  data?: MyPassageListResponse
}
