/**
 * Generated by orval — do not edit manually.
 */
import type { OpinionListResponse } from './opinionListResponse'

export interface DataResponseOpinionListResponse {
  data?: OpinionListResponse
}
