/**
 * Generated by orval — do not edit manually.
 */
import type { MyOpinionListResponse } from './myOpinionListResponse'

export interface DataResponseMyOpinionListResponse {
  data?: MyOpinionListResponse
}
