/**
 * Generated by orval — do not edit manually.
 */
import type { LikedOpinionListResponse } from './likedOpinionListResponse'

export interface DataResponseLikedOpinionListResponse {
  data?: LikedOpinionListResponse
}
