/**
 * Generated by orval — do not edit manually.
 */

export type DecorationRequestEffectType =
  (typeof DecorationRequestEffectType)[keyof typeof DecorationRequestEffectType]

export const DecorationRequestEffectType = {
  UNDERLINE: 'UNDERLINE',
  WAVY: 'WAVY',
  HIGHLIGHT: 'HIGHLIGHT',
  DOTTED: 'DOTTED',
  DOUBLE_LINE: 'DOUBLE_LINE',
  CIRCLE: 'CIRCLE',
} as const
