/**
 * Generated by orval — do not edit manually.
 */
import type { DecorationResponseEffectType } from './decorationResponseEffectType'

export interface DecorationResponse {
  decorationId?: number
  startOffset?: number
  endOffset?: number
  effectType?: DecorationResponseEffectType
  color?: string
}
