/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */
import type { DecorationRequestEffectType } from './decorationRequestEffectType'

export interface DecorationRequest {
  startOffset?: number
  endOffset?: number
  effectType: DecorationRequestEffectType
  color?: string
}
