/**
 * Generated by orval — do not edit manually.
 */
import type { DecorationRequestEffectType } from './decorationRequestEffectType'

export interface DecorationRequest {
  startOffset?: number
  endOffset?: number
  effectType: DecorationRequestEffectType
  color?: string
}
