/**
 * Generated by orval — do not edit manually.
 */

export type DecorationResponseEffectType =
  (typeof DecorationResponseEffectType)[keyof typeof DecorationResponseEffectType]

export const DecorationResponseEffectType = {
  UNDERLINE: 'UNDERLINE',
  WAVY: 'WAVY',
  HIGHLIGHT: 'HIGHLIGHT',
  DOTTED: 'DOTTED',
  DOUBLE_LINE: 'DOUBLE_LINE',
  CIRCLE: 'CIRCLE',
} as const
