/**
 * Generated by orval — do not edit manually.
 */

export type DecorationResponseEffectType =
  (typeof DecorationResponseEffectType)[keyof typeof DecorationResponseEffectType]

export const DecorationResponseEffectType = {
  UNDERLINE: 'UNDERLINE',
  WAVY: 'WAVY',
  HIGHLIGHT: 'HIGHLIGHT',
} as const
