/**
 * Generated by orval — do not edit manually.
 */
import type { DecorationResponse } from './decorationResponse'

export interface Detail {
  passageId?: number
  pageNumber?: number
  quotedText?: string
  isSpoiler?: boolean
  decorations?: DecorationResponse[]
}
