/**
 * Generated by orval — do not edit manually.
 */
import type { ExternalBookResponse } from './externalBookResponse'
import type { PageInfo } from './pageInfo'

export interface ExternalBookListResponse {
  books?: ExternalBookResponse[]
  pageInfo?: PageInfo
}
