/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */

export interface ExternalBookResponse {
  title?: string
  author?: string
  publisher?: string
  /**
   * 응답 속도를 위해 채우지 않으며 항상 null입니다.
   * @nullable
   */
  pageCount?: number | null
  isbn?: string
  coverImageUrl?: string
}
