/**
 * Generated by orval — do not edit manually.
 */
import type { BookOptionResponse } from './bookOptionResponse'
import type { PageInfo } from './pageInfo'

export interface FilterBooksResponse {
  books: BookOptionResponse[]
  pageInfo: PageInfo
}
