/**
 * Generated by orval — do not edit manually.
 */
import type { GetFilterBooksType } from './getFilterBooksType'

export type GetFilterBooksParams = {
  /**
   * 필터 종류 (LIKE: 좋아요 관리, SPOILER: 스포일러 대목 관리)
   */
  type: GetFilterBooksType
}
