/**
 * Generated by orval — do not edit manually.
 */

export type GetFilterBooksType = (typeof GetFilterBooksType)[keyof typeof GetFilterBooksType]

export const GetFilterBooksType = {
  LIKE: 'LIKE',
  SPOILER: 'SPOILER',
} as const
