/**
 * Generated by orval — do not edit manually.
 */

export type GetHomeCarouselBooksParams = {
  /**
   * 조회 시작 위치 (0부터 시작). 생략하면 전체 목록 중 가운데를 기준으로 조회
   */
  offset?: number
  /**
   * 조회 개수 (기본값 20, 최대 100)
   */
  size?: number
}
