/**
 * Generated by orval — do not edit manually.
 */

export type GetMyLibraryBooksParams = {
  /**
   * 조회 시작 위치 (0부터 시작). 생략하면 가장 최근에 흔적을 남긴 도서부터 조회
   */
  offset?: number
  /**
   * 조회 개수 (기본값 20, 최대 100)
   */
  size?: number
}
