/**
 * Generated by orval — do not edit manually.
 */
import type { GetMyLibraryBooksOpinionCountScope } from './getMyLibraryBooksOpinionCountScope'

export type GetMyLibraryBooksParams = {
  /**
   * 페이지 번호 (0부터 시작, 기본값 0)
   */
  page?: number
  /**
   * 페이지 크기 (기본값 20, 최대 100)
   */
  size?: number
  /**
   * 흔적 수 집계 기준 (ALL: 도서 전체, MINE: 로그인 사용자 본인, 기본값 ALL)
   */
  opinionCountScope?: GetMyLibraryBooksOpinionCountScope
}
