/**
 * Generated by orval — do not edit manually.
 */

export type GetMyLibraryBooksOpinionCountScope =
  (typeof GetMyLibraryBooksOpinionCountScope)[keyof typeof GetMyLibraryBooksOpinionCountScope]

export const GetMyLibraryBooksOpinionCountScope = {
  ALL: 'ALL',
  MINE: 'MINE',
} as const
