/**
 * Generated by orval — do not edit manually.
 */

export type GetNoticesParams = {
  /**
   * 페이지 번호 (0부터 시작, 기본값 0)
   */
  page?: number
  /**
   * 페이지 크기 (기본값 20, 최대 100)
   */
  size?: number
}
