/**
 * Generated by orval — do not edit manually.
 */

export type GetOpinionsSortType = (typeof GetOpinionsSortType)[keyof typeof GetOpinionsSortType]

export const GetOpinionsSortType = {
  LATEST: 'LATEST',
  LIKES: 'LIKES',
} as const
