/**
 * Generated by orval — do not edit manually.
 */
import type { GetOpinionsSortType } from './getOpinionsSortType'

export type GetOpinionsParams = {
  /**
   * 정렬 기준 (LATEST: 최신순(기본), LIKES: 좋아요순)
   */
  sortType?: GetOpinionsSortType
  /**
   * 페이지 번호 (0부터 시작, 기본값 0)
   */
  page?: number
  /**
   * 페이지 크기 (기본값 20, 최대 100)
   */
  size?: number
}
