/**
 * Generated by orval — do not edit manually.
 */
import type { GroupMemberResponse } from './groupMemberResponse'
import type { PageInfo } from './pageInfo'

export interface GroupMemberListResponse {
  members: GroupMemberResponse[]
  pageInfo: PageInfo
}
