/**
 * Generated by orval — do not edit manually.
 */

export interface GroupDetailResponse {
  groupId: number
  name: string
  bookId: number
  bookTitle: string
  bookAuthor: string
  /** @nullable */
  bookCoverImageUrl?: string | null
  hostUserId: number
  hostNickname: string
  capacity: number
  memberCount: number
  startDate: string
  endDate: string
  /** 종료일이 지났는지 여부. 안내용 배지 표시에만 쓰이며, 이 값이 true여도 모임 목록 노출/흔적·의견 작성 등은 계속 가능합니다. */
  ended: boolean
  /** 현재 로그인한 유저가 이 모임의 모임장인지 여부. 방 설정 변경 등 모임장 전용 화면 노출 여부를 프론트에서 판단하는 데 사용합니다. */
  isHost: boolean
}
