/**
 * Generated by orval — do not edit manually.
 */

export type GroupMemberResponseRole =
  (typeof GroupMemberResponseRole)[keyof typeof GroupMemberResponseRole]

export const GroupMemberResponseRole = {
  HOST: 'HOST',
  MEMBER: 'MEMBER',
} as const
