/**
 * Generated by orval — do not edit manually.
 */

export interface GroupInvitationPreviewResponse {
  groupId: number
  name: string
  bookTitle: string
  bookAuthor: string
  /** @nullable */
  bookCoverImageUrl?: string | null
  capacity: number
  memberCount: number
  /** 정원이 가득 차 더 이상 가입할 수 없는지 여부 */
  full: boolean
  /** 요청자가 이미 이 모임의 멤버인지 여부. 비로그인 요청이면 항상 false. */
  alreadyJoined: boolean
}
