/**
 * Generated by orval — do not edit manually.
 */
import type { GroupMemberResponseRole } from './groupMemberResponseRole'

export interface GroupMemberResponse {
  userId: number
  nickname: string
  /** @nullable */
  profileImageUrl?: string | null
  role: GroupMemberResponseRole
  joinedAt: string
}
