/**
 * Generated by orval — do not edit manually.
 */
import type { GroupSummaryResponse } from './groupSummaryResponse'
import type { PageInfo } from './pageInfo'

export interface GroupListResponse {
  groups: GroupSummaryResponse[]
  pageInfo: PageInfo
}
