/**
 * Generated by orval — do not edit manually.
 */
import type { LikedOpinionResponse } from './likedOpinionResponse'
import type { PageInfo } from './pageInfo'

export interface LikedOpinionListResponse {
  opinions?: LikedOpinionResponse[]
  pageInfo?: PageInfo
}
