/**
 * Generated by orval — do not edit manually.
 */

export interface LikedOpinionResponse {
  opinionId?: number
  bookId?: number
  bookTitle?: string
  bookCoverImageUrl?: string
  passageId?: number
  quotedText?: string
  pageNumber?: number
  content?: string
  likeCount?: number
  createdAt?: string
  likedAt?: string
}
