/**
 * Generated by orval — do not edit manually.
 */

export interface LoginResponse {
  accessToken: string
  refreshToken: string
  isNewUser: boolean
  termsAgreed: boolean
  hasCompletedOnboarding: boolean
}
