/**
 * Generated by orval — do not edit manually.
 */
import type { MeResponseSnsProvider } from './meResponseSnsProvider'

export interface MeResponse {
  userId?: number
  nickname?: string
  profileImageUrl?: string
  backgroundColor?: string
  snsProvider?: MeResponseSnsProvider
  opinionCount?: number
}
