/**
 * Generated by orval — do not edit manually.
 */

export type MeResponseSnsProvider =
  (typeof MeResponseSnsProvider)[keyof typeof MeResponseSnsProvider]

export const MeResponseSnsProvider = {
  KAKAO: 'KAKAO',
  APPLE: 'APPLE',
} as const
