/**
 * Generated by orval — do not edit manually.
 */
import type { MeResponseSnsProvider } from './meResponseSnsProvider'

export interface MeResponse {
  userId: number
  nickname: string
  /** @nullable */
  email?: string | null
  /** @nullable */
  profileImageUrl?: string | null
  /** @nullable */
  backgroundColor?: string | null
  snsProvider: MeResponseSnsProvider
  opinionCount: number
}
