/**
 * Generated by orval — do not edit manually.
 */
import type { MyOpinionResponse } from './myOpinionResponse'
import type { PageInfo } from './pageInfo'

export interface MyOpinionListResponse {
  opinions?: MyOpinionResponse[]
  pageInfo?: PageInfo
}
