/**
 * Generated by orval — do not edit manually.
 */

export interface MyOpinionResponse {
  opinionId: number
  bookId: number
  bookTitle: string
  /** @nullable */
  bookCoverImageUrl?: string | null
  passageId: number
  quotedText: string
  pageNumber: number
  content: string
  likeCount: number
  createdAt: string
}
