/**
 * Generated by orval — do not edit manually.
 */
import type { MyPassageResponse } from './myPassageResponse'
import type { PageInfo } from './pageInfo'

export interface MyPassageListResponse {
  passages: MyPassageResponse[]
  pageInfo: PageInfo
}
