/**
 * Generated by orval — do not edit manually.
 */

export interface MyPassageResponse {
  passageId: number
  bookId: number
  pageNumber: number
  quotedText: string
  isSpoiler: boolean
  createdAt: string
}
