/**
 * Generated by orval — do not edit manually.
 */
import type { NoticeResponse } from './noticeResponse'
import type { PageInfo } from './pageInfo'

export interface NoticeListResponse {
  notices?: NoticeResponse[]
  pageInfo?: PageInfo
}
