/**
 * Generated by orval — do not edit manually.
 */
import type { NotificationResponseType } from './notificationResponseType'

export interface NotificationResponse {
  notificationId: number
  type: NotificationResponseType
  title: string
  body: string
  /** @nullable */
  opinionId?: number | null
  /** @nullable */
  bookId?: number | null
  /** @nullable */
  commentId?: number | null
  isRead: boolean
  createdAt: string
}
