/**
 * Generated by orval — do not edit manually.
 */
import type { NotificationResponse } from './notificationResponse'
import type { PageInfo } from './pageInfo'

export interface NotificationListResponse {
  notifications: NotificationResponse[]
  pageInfo: PageInfo
}
