/**
 * Generated by orval — do not edit manually.
 */

export type NotificationResponseType =
  (typeof NotificationResponseType)[keyof typeof NotificationResponseType]

export const NotificationResponseType = {
  OPINION_LIKED: 'OPINION_LIKED',
  OPINION_COMMENTED: 'OPINION_COMMENTED',
  BOOK_NEW_OPINIONS: 'BOOK_NEW_OPINIONS',
} as const
