/**
 * Generated by orval — do not edit manually.
 */
import type { OpinionSummaryResponse } from './opinionSummaryResponse'
import type { PageInfo } from './pageInfo'

export interface OpinionListResponse {
  opinions: OpinionSummaryResponse[]
  pageInfo: PageInfo
}
