/**
 * Generated by orval — do not edit manually.
 */

export interface OpinionSummaryResponse {
  opinionId?: number
  userId?: number
  nickname?: string
  content?: string
  likeCount?: number
  createdAt?: string
}
