/**
 * Generated by orval — do not edit manually.
 */
import type { DecorationResponse } from './decorationResponse'

export interface OpinionResponse {
  opinionId?: number
  passageId?: number
  merged?: boolean
  content?: string
  decorations?: DecorationResponse[]
  createdAt?: string
}
