/**
 * Generated by orval — do not edit manually.
 */
import type { PageInfo } from './pageInfo'

export interface PageNumbers {
  bookTitle: string
  coverImageUrl?: string
  pageNumbers: number[]
  pageInfo: PageInfo
}
