/**
 * Generated by orval — do not edit manually.
 */
import type { PolicyResponsePolicyType } from './policyResponsePolicyType'

export interface PolicyResponse {
  policyType: PolicyResponsePolicyType
  content: string
  updatedAt: string
}
