/**
 * Generated by orval — do not edit manually.
 */

export type PolicyResponsePolicyType =
  (typeof PolicyResponsePolicyType)[keyof typeof PolicyResponsePolicyType]

export const PolicyResponsePolicyType = {
  TERMS: 'TERMS',
  PRIVACY: 'PRIVACY',
} as const
