/**
 * Generated by orval — do not edit manually.
 */

export type RegisterDeviceTokenRequestPlatform =
  (typeof RegisterDeviceTokenRequestPlatform)[keyof typeof RegisterDeviceTokenRequestPlatform]

export const RegisterDeviceTokenRequestPlatform = {
  IOS: 'IOS',
  ANDROID: 'ANDROID',
} as const
