/**
 * Generated by orval — do not edit manually.
 */
import type { RegisterDeviceTokenRequestPlatform } from './registerDeviceTokenRequestPlatform'

export interface RegisterDeviceTokenRequest {
  /**
   * @minLength 0
   * @maxLength 255
   */
  token: string
  platform: RegisterDeviceTokenRequestPlatform
}
