/**
 * Generated by orval — do not edit manually.
 */

export type ReportResponseReason = (typeof ReportResponseReason)[keyof typeof ReportResponseReason]

export const ReportResponseReason = {
  SPAM: 'SPAM',
  HATE: 'HATE',
  ABUSE: 'ABUSE',
  COPYRIGHT: 'COPYRIGHT',
  ETC: 'ETC',
} as const
