/**
 * Generated by orval — do not edit manually.
 */
import type { ReportResponseReason } from './reportResponseReason'
import type { ReportResponseTargetType } from './reportResponseTargetType'

export interface ReportResponse {
  reportId: number
  targetType: ReportResponseTargetType
  targetId: number
  reason: ReportResponseReason
  /** @nullable */
  detail?: string | null
  createdAt: string
}
