/**
 * Generated by orval — do not edit manually.
 */

export type ReportResponseTargetType =
  (typeof ReportResponseTargetType)[keyof typeof ReportResponseTargetType]

export const ReportResponseTargetType = {
  OPINION: 'OPINION',
  COMMENT: 'COMMENT',
} as const
