/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */
import type { CommentResponse } from './commentResponse'

export interface RootCommentResponse {
  commentId?: number
  userId?: number
  nickname?: string
  profileImageUrl?: string
  content?: string
  isDeleted?: boolean
  createdAt?: string
  updatedAt?: string
  replies?: CommentResponse[]
  replyCount?: number
  hasMoreReplies?: boolean
}
