/**
 * Generated by orval — do not edit manually.
 */
import type { CommentResponse } from './commentResponse'

export interface RootCommentResponse {
  commentId?: number
  userId?: number
  nickname?: string
  profileImageUrl?: string
  content?: string
  isDeleted?: boolean
  createdAt?: string
  updatedAt?: string
  replies?: CommentResponse[]
  replyCount?: number
  hasMoreReplies?: boolean
}
