/**
 * Generated by orval — do not edit manually.
 */
import type { PageInfo } from './pageInfo'
import type { RootCommentResponse } from './rootCommentResponse'

export interface RootCommentListResponse {
  comments?: RootCommentResponse[]
  pageInfo?: PageInfo
}
