/**
 * Generated by orval — do not edit manually.
 */

export type SearchInternalBooksParams = {
  /**
   * 검색 키워드 (빈 문자열이면 전체 목록)
   */
  keyword: string
  /**
   * 페이지 번호 (0부터 시작, 기본값 0)
   */
  page?: number
  /**
   * 페이지 크기 (기본값 20, 최대 100)
   */
  size?: number
}
