/**
 * Generated by orval — do not edit manually.
 */
import type { SearchInternalBooksSort } from './searchInternalBooksSort'

export type SearchInternalBooksParams = {
  /**
   * 검색 키워드 (빈 문자열이면 전체 목록)
   */
  keyword: string
  /**
   * 정렬 기준 (NAME: 이름순, RECENT: 최신 흔적순, OPINION: 흔적 많은 순, 기본값 RECENT)
   */
  sort?: SearchInternalBooksSort
  /**
   * 페이지 번호 (0부터 시작, 기본값 0)
   */
  page?: number
  /**
   * 페이지 크기 (기본값 20, 최대 100)
   */
  size?: number
}
