/**
 * Generated by orval — do not edit manually.
 */

export type SearchInternalBooksSort =
  (typeof SearchInternalBooksSort)[keyof typeof SearchInternalBooksSort]

export const SearchInternalBooksSort = {
  NAME: 'NAME',
  RECENT: 'RECENT',
  OPINION: 'OPINION',
} as const
