/**
 * Generated by orval — do not edit manually.
 */
import type { BoundingBox } from './boundingBox'

export interface TextBlock {
  text?: string
  boundingBox?: BoundingBox
  lineBreak?: boolean
}
