/**
 * Generated by orval — do not edit manually.
 */

export type UpdateUserBookStatusRequestStatus =
  (typeof UpdateUserBookStatusRequestStatus)[keyof typeof UpdateUserBookStatusRequestStatus]

export const UpdateUserBookStatusRequestStatus = {
  READING: 'READING',
  PLANNED: 'PLANNED',
} as const
