/**
 * Generated by orval — do not edit manually.
 */
import type { UpdateUserBookStatusRequestStatus } from './updateUserBookStatusRequestStatus'

export interface UpdateUserBookStatusRequest {
  bookId: number
  status: UpdateUserBookStatusRequestStatus
  currentPage?: number
}
