/**
 * Generated by orval — do not edit manually.
 */

export type UserBookStatusResponseStatus =
  (typeof UserBookStatusResponseStatus)[keyof typeof UserBookStatusResponseStatus]

export const UserBookStatusResponseStatus = {
  READING: 'READING',
  PLANNED: 'PLANNED',
} as const
