/**
 * Generated by orval — do not edit manually.
 */
import type { UserBookStatusResponseStatus } from './userBookStatusResponseStatus'

export interface UserBookStatusResponse {
  bookId?: number
  status?: UserBookStatusResponseStatus
  currentPage?: number
}
