/**
 * Generated by orval — do not edit manually.
 */
import type { DataResponsePolicyResponse } from '../models/dataResponsePolicyResponse'

import { customFetch } from '../../customFetch.api'

export const getGetPolicyUrl = (type: 'TERMS' | 'PRIVACY') => {
  return `/api/policies/${type}`
}

/**
 * 이용약관 또는 개인정보처리방침을 markdown 형태로 조회합니다.
 * @summary 약관 조회
 */
export const getPolicy = async (
  type: 'TERMS' | 'PRIVACY',
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponsePolicyResponse> => {
  return customFetch<DataResponsePolicyResponse>(getGetPolicyUrl(type), {
    ...options,
    method: 'GET',
  })
}
