/**
 * Generated by orval — do not edit manually.
 */
import type { CreateGroupRequest } from '../models/createGroupRequest'

import type { DataResponseGroupDetailResponse } from '../models/dataResponseGroupDetailResponse'

import type { DataResponseGroupInvitationPreviewResponse } from '../models/dataResponseGroupInvitationPreviewResponse'

import type { DataResponseGroupInviteLinkResponse } from '../models/dataResponseGroupInviteLinkResponse'

import type { DataResponseGroupListResponse } from '../models/dataResponseGroupListResponse'

import type { DataResponseGroupMemberListResponse } from '../models/dataResponseGroupMemberListResponse'

import type { DataResponseVoid } from '../models/dataResponseVoid'

import type { GetGroupMembersParams } from '../models/getGroupMembersParams'

import type { GetMyGroupsParams } from '../models/getMyGroupsParams'

import type { UpdateGroupRequest } from '../models/updateGroupRequest'

import { customFetch } from '../../customFetch.api'

export const getGetMyGroupsUrl = (params?: GetMyGroupsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/api/groups?${stringifiedParams}` : `/api/groups`
}

/**
 * 현재 로그인한 사용자가 속한 모임을 최근 생성 순으로 조회합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 내 모임 목록
 */
export const getMyGroups = async (
  params?: GetMyGroupsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseGroupListResponse> => {
  return customFetch<DataResponseGroupListResponse>(getGetMyGroupsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getCreateGroupUrl = () => {
  return `/api/groups`
}

/**
 * 책 1권을 고정해 모임을 만듭니다. 생성한 사용자는 모임장(HOST)으로 자동 가입됩니다. 책은 생성 이후 변경할 수 없습니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 모임 생성
 */
export const createGroup = async (
  createGroupRequest: CreateGroupRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseGroupDetailResponse> => {
  return customFetch<DataResponseGroupDetailResponse>(getCreateGroupUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createGroupRequest),
  })
}

export const getRegenerateInviteLinkUrl = (groupId: number) => {
  return `/api/groups/${groupId}/invite-link/regenerate`
}

/**
 * 모임장만 재발급할 수 있습니다. 재발급하면 기존 초대 코드는 즉시 무효화됩니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 초대 링크 재발급
 */
export const regenerateInviteLink = async (
  groupId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseGroupInviteLinkResponse> => {
  return customFetch<DataResponseGroupInviteLinkResponse>(getRegenerateInviteLinkUrl(groupId), {
    ...options,
    method: 'POST',
  })
}

export const getJoinGroupUrl = (inviteCode: string) => {
  return `/api/groups/invitations/${inviteCode}/join`
}

/**
 * 정원이 가득 찼거나 이미 가입한 모임이면 가입할 수 없습니다. 모임 기간이 지났어도 가입할 수 있습니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 초대 링크로 모임 가입
 */
export const joinGroup = async (
  inviteCode: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseGroupDetailResponse> => {
  return customFetch<DataResponseGroupDetailResponse>(getJoinGroupUrl(inviteCode), {
    ...options,
    method: 'POST',
  })
}

export const getGetGroupDetailUrl = (groupId: number) => {
  return `/api/groups/${groupId}`
}

/**
 * 모임원만 조회할 수 있습니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 모임 상세 조회
 */
export const getGroupDetail = async (
  groupId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseGroupDetailResponse> => {
  return customFetch<DataResponseGroupDetailResponse>(getGetGroupDetailUrl(groupId), {
    ...options,
    method: 'GET',
  })
}

export const getDeleteGroupUrl = (groupId: number) => {
  return `/api/groups/${groupId}`
}

/**
 * 모임장만 모임을 삭제할 수 있습니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 모임 삭제
 */
export const deleteGroup = async (
  groupId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getDeleteGroupUrl(groupId), {
    ...options,
    method: 'DELETE',
  })
}

export const getUpdateGroupUrl = (groupId: number) => {
  return `/api/groups/${groupId}`
}

/**
 * 모임장만 이름/인원/기간을 수정할 수 있습니다. 책은 대상이 아닙니다. 인원은 현재 참여 인원보다 적게 줄일 수 없습니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 방 설정 변경
 */
export const updateGroup = async (
  groupId: number,
  updateGroupRequest: UpdateGroupRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseGroupDetailResponse> => {
  return customFetch<DataResponseGroupDetailResponse>(getUpdateGroupUrl(groupId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateGroupRequest),
  })
}

export const getGetGroupMembersUrl = (groupId: number, params?: GetGroupMembersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/groups/${groupId}/members?${stringifiedParams}`
    : `/api/groups/${groupId}/members`
}

/**
 * 모임원만 조회할 수 있습니다. 모임장이 먼저, 그다음 가입 순으로 정렬됩니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 모임 멤버 목록
 */
export const getGroupMembers = async (
  groupId: number,
  params?: GetGroupMembersParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseGroupMemberListResponse> => {
  return customFetch<DataResponseGroupMemberListResponse>(getGetGroupMembersUrl(groupId, params), {
    ...options,
    method: 'GET',
  })
}

export const getGetInviteLinkUrl = (groupId: number) => {
  return `/api/groups/${groupId}/invite-link`
}

/**
 * 모임장만 조회할 수 있습니다. 초대 코드는 별도 만료 시각이 없고 모임 기간과도 무관하게 계속 유효합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 초대 링크 조회
 */
export const getInviteLink = async (
  groupId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseGroupInviteLinkResponse> => {
  return customFetch<DataResponseGroupInviteLinkResponse>(getGetInviteLinkUrl(groupId), {
    ...options,
    method: 'GET',
  })
}

export const getPreviewInvitationUrl = (inviteCode: string) => {
  return `/api/groups/invitations/${inviteCode}`
}

/**
 * 초대 링크를 열었을 때 가입 전 모임 정보를 보여줍니다. 인증 불필요. Authorization: Bearer {accessToken} 헤더를 보내면 alreadyJoined(이미 가입 여부)도 함께 내려줍니다.
 * @summary 초대 링크 미리보기
 */
export const previewInvitation = async (
  inviteCode: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseGroupInvitationPreviewResponse> => {
  return customFetch<DataResponseGroupInvitationPreviewResponse>(
    getPreviewInvitationUrl(inviteCode),
    {
      ...options,
      method: 'GET',
    },
  )
}
