/**
 * Generated by orval — do not edit manually.
 */
import type { AppleLoginRequest } from '../models/appleLoginRequest'

import type { DataResponseLoginResponse } from '../models/dataResponseLoginResponse'

import type { DataResponseTermsAgreementResponse } from '../models/dataResponseTermsAgreementResponse'

import type { DataResponseTokenResponse } from '../models/dataResponseTokenResponse'

import type { DataResponseVoid } from '../models/dataResponseVoid'

import type { KakaoLoginRequest } from '../models/kakaoLoginRequest'

import type { RefreshTokenRequest } from '../models/refreshTokenRequest'

import { customFetch } from '../../customFetch.api'

export const getAgreeToTermsUrl = () => {
  return `/api/auth/terms`
}

/**
 * 이용약관 + 개인정보 수집·이용 동의를 1회 처리로 기록합니다(FR-AUTH-03). 이미 동의한 사용자가 다시 호출해도 동의 시각만 갱신되며 에러는 발생하지 않습니다.
 * @summary 약관 동의
 */
export const agreeToTerms = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseTermsAgreementResponse> => {
  return customFetch<DataResponseTermsAgreementResponse>(getAgreeToTermsUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getRefreshUrl = () => {
  return `/api/auth/refresh`
}

/**
 * 리프레시 토큰으로 새 액세스 토큰 + 리프레시 토큰을 발급합니다. 기존 리프레시 토큰은 사용 즉시 폐기됩니다(재사용 불가).
 * @summary 토큰 재발급
 */
export const refresh = async (
  refreshTokenRequest: RefreshTokenRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseTokenResponse> => {
  return customFetch<DataResponseTokenResponse>(getRefreshUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshTokenRequest),
  })
}

export const getLogoutUrl = () => {
  return `/api/auth/logout`
}

/**
 * 전달한 리프레시 토큰을 폐기합니다. 액세스 토큰 자체는 만료 전까지 유효하지만, 재발급에는 더 이상 사용할 수 없습니다.
 * @summary 로그아웃
 */
export const logout = async (
  refreshTokenRequest: RefreshTokenRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getLogoutUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshTokenRequest),
  })
}

export const getLoginWithKakaoUrl = () => {
  return `/api/auth/kakao`
}

/**
 * 모바일 앱이 카카오 SDK로 로그인해 받은 카카오 액세스 토큰을 전달하면, 카카오 사용자 정보 API로 직접 검증한 뒤 가입/로그인을 처리하고 서비스 자체 JWT를 발급합니다. 처음 로그인하는 사용자는 닉네임이 자동 생성되며(isNewUser=true), 약관 동의는 별도로 POST /api/auth/terms를 호출해야 합니다.
 * @summary 카카오 로그인
 */
export const loginWithKakao = async (
  kakaoLoginRequest: KakaoLoginRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseLoginResponse> => {
  return customFetch<DataResponseLoginResponse>(getLoginWithKakaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kakaoLoginRequest),
  })
}

export const getLoginWithAppleUrl = () => {
  return `/api/auth/apple`
}

/**
 * 웹(Apple JS SDK) 또는 iOS 앱(네이티브 Sign in with Apple)에서 발급받은 identity token(JWT)을 전달하면, Apple 공개키(JWKS)로 서명을 직접 검증한 뒤 가입/로그인을 처리하고 서비스 자체 JWT를 발급합니다. aud 클레임은 설정된 웹 Service ID 또는 앱 Bundle ID 중 하나와 일치해야 합니다. authorizationCode를 함께 전달하면 회원탈퇴 시 애플 연동 해제(revoke)에 쓸 refresh token을 미리 확보해둡니다(실패해도 로그인은 계속 진행됩니다). givenName/familyName은 애플이 최초 로그인 시에만 내려주는 값으로, 이후 로그인엔 null이어도 됩니다. 처음 로그인하는 사용자는 닉네임이 자동 생성되며(isNewUser=true), 약관 동의는 별도로 POST /api/auth/terms를 호출해야 합니다.
 * @summary 애플 로그인
 */
export const loginWithApple = async (
  appleLoginRequest: AppleLoginRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseLoginResponse> => {
  return customFetch<DataResponseLoginResponse>(getLoginWithAppleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(appleLoginRequest),
  })
}
