/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */
import type {
  DataResponseLoginResponse,
  DataResponseTermsAgreementResponse,
  DataResponseTokenResponse,
  DataResponseVoid,
  KakaoLoginRequest,
  RefreshTokenRequest,
} from '../models'

import { customFetch } from '../../customFetch.api'

export const getAgreeToTermsUrl = () => {
  return `/api/auth/terms`
}

/**
 * 이용약관 + 개인정보 수집·이용 동의를 1회 처리로 기록합니다(FR-AUTH-03). 이미 동의한 사용자가 다시 호출해도 동의 시각만 갱신되며 에러는 발생하지 않습니다.
 * @summary 약관 동의
 */
export const agreeToTerms = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseTermsAgreementResponse> => {
  return customFetch<DataResponseTermsAgreementResponse>(getAgreeToTermsUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getRefreshUrl = () => {
  return `/api/auth/refresh`
}

/**
 * 리프레시 토큰으로 새 액세스 토큰 + 리프레시 토큰을 발급합니다. 기존 리프레시 토큰은 사용 즉시 폐기됩니다(재사용 불가).
 * @summary 토큰 재발급
 */
export const refresh = async (
  refreshTokenRequest: RefreshTokenRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseTokenResponse> => {
  return customFetch<DataResponseTokenResponse>(getRefreshUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshTokenRequest),
  })
}

export const getLogoutUrl = () => {
  return `/api/auth/logout`
}

/**
 * 전달한 리프레시 토큰을 폐기합니다. 액세스 토큰 자체는 만료 전까지 유효하지만, 재발급에는 더 이상 사용할 수 없습니다.
 * @summary 로그아웃
 */
export const logout = async (
  refreshTokenRequest: RefreshTokenRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getLogoutUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshTokenRequest),
  })
}

export const getLoginWithKakaoUrl = () => {
  return `/api/auth/kakao`
}

/**
 * 모바일 앱이 카카오 SDK로 로그인해 받은 카카오 액세스 토큰을 전달하면, 카카오 사용자 정보 API로 직접 검증한 뒤 가입/로그인을 처리하고 서비스 자체 JWT를 발급합니다. 처음 로그인하는 사용자는 닉네임이 자동 생성되며(isNewUser=true), 약관 동의는 별도로 POST /api/auth/terms를 호출해야 합니다.
 * @summary 카카오 로그인
 */
export const loginWithKakao = async (
  kakaoLoginRequest: KakaoLoginRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseLoginResponse> => {
  return customFetch<DataResponseLoginResponse>(getLoginWithKakaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kakaoLoginRequest),
  })
}
