/**
 * Generated by orval — do not edit manually.
 */
import type { DataResponseFilterBooksResponse } from '../models/dataResponseFilterBooksResponse'

import type { DataResponseLikedOpinionListResponse } from '../models/dataResponseLikedOpinionListResponse'

import type { DataResponseMeResponse } from '../models/dataResponseMeResponse'

import type { DataResponseMyOpinionListResponse } from '../models/dataResponseMyOpinionListResponse'

import type { DataResponseMyPassageListResponse } from '../models/dataResponseMyPassageListResponse'

import type { DataResponseOnboardingCompleteResponse } from '../models/dataResponseOnboardingCompleteResponse'

import type { DataResponseVoid } from '../models/dataResponseVoid'

import type { GetFilterBooksParams } from '../models/getFilterBooksParams'

import type { GetLikedOpinionsParams } from '../models/getLikedOpinionsParams'

import type { GetMyOpinionsParams } from '../models/getMyOpinionsParams'

import type { GetMyPassagesParams } from '../models/getMyPassagesParams'

import type { ModifyProfileImageBody } from '../models/modifyProfileImageBody'

import type { UpdateBackgroundColorRequest } from '../models/updateBackgroundColorRequest'

import type { UpdateNicknameRequest } from '../models/updateNicknameRequest'

import { customFetch } from '../../customFetch.api'

export const getModifyProfileImageUrl = () => {
  return `/api/users/me/profile-image`
}

/**
 * 프로필 이미지를 업로드하여 변경합니다(jpeg/png). Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 프로필 이미지 변경
 */
export const modifyProfileImage = async (
  modifyProfileImageBody?: ModifyProfileImageBody,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseMeResponse> => {
  const formData = new FormData()
  if (modifyProfileImageBody?.image !== undefined) {
    formData.append(`image`, modifyProfileImageBody.image)
  }

  return customFetch<DataResponseMeResponse>(getModifyProfileImageUrl(), {
    ...options,
    method: 'PATCH',
    body: formData,
  })
}

export const getCompleteOnboardingUrl = () => {
  return `/api/users/me/onboarding-complete`
}

/**
 * 로그인 직후 온보딩 4단계를 마치면 호출합니다(FR-AUTH-05). 이미 완료한 사용자가 다시 호출해도 에러 없이 그대로 완료 상태를 유지합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 온보딩 완료 처리
 */
export const completeOnboarding = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseOnboardingCompleteResponse> => {
  return customFetch<DataResponseOnboardingCompleteResponse>(getCompleteOnboardingUrl(), {
    ...options,
    method: 'PATCH',
  })
}

export const getModifyNicknameUrl = () => {
  return `/api/users/me/nickname`
}

/**
 * 최대 15자, 중복 불가, 하루 1회만 변경할 수 있습니다(달력일 기준). Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 닉네임 변경
 */
export const modifyNickname = async (
  updateNicknameRequest: UpdateNicknameRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseMeResponse> => {
  return customFetch<DataResponseMeResponse>(getModifyNicknameUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateNicknameRequest),
  })
}

export const getModifyBackgroundColorUrl = () => {
  return `/api/users/me/background-color`
}

/**
 * 흔적 보기 화면의 배경색을 변경합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 배경색 변경
 */
export const modifyBackgroundColor = async (
  updateBackgroundColorRequest: UpdateBackgroundColorRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseMeResponse> => {
  return customFetch<DataResponseMeResponse>(getModifyBackgroundColorUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateBackgroundColorRequest),
  })
}

export const getGetMeUrl = () => {
  return `/api/users/me`
}

/**
 * 닉네임, 이메일, 프로필 이미지, 배경색, 가입 경로(SNS), 지금까지 남긴 흔적 수를 조회합니다. 이메일은 SNS 이메일 동의 여부에 따라 없을 수 있습니다(null). Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 내 프로필 조회
 */
export const getMe = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseMeResponse> => {
  return customFetch<DataResponseMeResponse>(getGetMeUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getWithdrawUrl = () => {
  return `/api/users/me`
}

/**
 * 소프트 삭제 처리하고 닉네임을 익명화합니다(다른 이용자의 대화 맥락 유지를 위해 공개된 발췌·의견·댓글은 남습니다). 카카오 연동 해제를 함께 시도하나 실패해도 탈퇴 자체는 계속 진행되며(best-effort), 발급된 모든 리프레시 토큰은 즉시 무효화됩니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 회원 탈퇴
 */
export const withdraw = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getWithdrawUrl(), {
    ...options,
    method: 'DELETE',
  })
}

export const getGetMyPassagesUrl = (params?: GetMyPassagesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/users/me/passages?${stringifiedParams}`
    : `/api/users/me/passages`
}

/**
 * 내가 흔적을 남긴 대목을 최신순으로 조회합니다. 소유 기준은 최초 작성자가 아니라 해당 대목에 흔적을 남긴 사용자이며, 병합된 대목은 흔적을 남긴 모든 사용자에게 노출됩니다. bookId를 지정하면 해당 책으로 한정하고, 생략하면 전체 책을 대상으로 합니다. spoilerOnly=true면 스포일러 대목만 조회합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 내 대목 목록
 */
export const getMyPassages = async (
  params?: GetMyPassagesParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseMyPassageListResponse> => {
  return customFetch<DataResponseMyPassageListResponse>(getGetMyPassagesUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetMyOpinionsUrl = (params?: GetMyOpinionsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/users/me/opinions?${stringifiedParams}`
    : `/api/users/me/opinions`
}

/**
 * 내가 작성한 흔적을 최신순으로 조회합니다. bookId를 지정하면 해당 책의 흔적만 조회합니다(내 서재 책 상세 - 의견 탭). 생략하면 전체 책을 대상으로 합니다. 인증 불필요. Authorization: Bearer {accessToken} 헤더가 없으면(비로그인) 샘플 흔적 목록을 고정 응답으로 반환합니다.
 * @summary 내가 남긴 흔적 목록
 */
export const getMyOpinions = async (
  params?: GetMyOpinionsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseMyOpinionListResponse> => {
  return customFetch<DataResponseMyOpinionListResponse>(getGetMyOpinionsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetLikedOpinionsUrl = (params?: GetLikedOpinionsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/users/me/likes?${stringifiedParams}`
    : `/api/users/me/likes`
}

/**
 * 내가 좋아요를 누른 흔적을 좋아요 누른 순서대로(최신순) 조회합니다. bookId를 지정하면 해당 책의 좋아요만 조회합니다(내 서재 책 상세 - 좋아요 탭). 생략하면 전체 책을 대상으로 합니다(마이페이지 좋아요 관리 - 전체 책 보기). 좋아요 취소는 이 API가 아니라 흔적 좋아요 토글 API가 담당합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 좋아요 누른 흔적 목록
 */
export const getLikedOpinions = async (
  params?: GetLikedOpinionsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseLikedOpinionListResponse> => {
  return customFetch<DataResponseLikedOpinionListResponse>(getGetLikedOpinionsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetFilterBooksUrl = (params: GetFilterBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/users/me/filter-books?${stringifiedParams}`
    : `/api/users/me/filter-books`
}

/**
 * 좋아요 관리·스포일러 관리 화면의 "전체 책 보기" 드롭다운에 쓸 도서 목록입니다. type=LIKE면 내가 좋아요를 누른 흔적이 있는 도서를, type=SPOILER면 내가 스포일러로 남긴 대목이 있는 도서를 최근 활동순으로 중복 없이 반환합니다. 여기서 고른 bookId를 흔적/좋아요/대목 목록 API의 bookId 파라미터로 전달합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 도서 필터 목록
 */
export const getFilterBooks = async (
  params: GetFilterBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseFilterBooksResponse> => {
  return customFetch<DataResponseFilterBooksResponse>(getGetFilterBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}
