/**
 * Generated by orval — do not edit manually.
 */
import type { CreateReportRequest } from '../models/createReportRequest'

import type { DataResponseReportResponse } from '../models/dataResponseReportResponse'

import { customFetch } from '../../customFetch.api'

export const getReportOpinionUrl = (opinionId: number) => {
  return `/api/opinions/${opinionId}/reports`
}

/**
 * 흔적을 사유(스팸/혐오/욕설/저작권/기타)와 함께 신고합니다. 기타 사유는 상세 내용이 필수입니다. 본인이 작성한 흔적, 이미 신고한 흔적은 신고할 수 없습니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 흔적 신고
 */
export const reportOpinion = async (
  opinionId: number,
  createReportRequest: CreateReportRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseReportResponse> => {
  return customFetch<DataResponseReportResponse>(getReportOpinionUrl(opinionId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReportRequest),
  })
}

export const getReportCommentUrl = (commentId: number) => {
  return `/api/comments/${commentId}/reports`
}

/**
 * 댓글/답글을 사유(스팸/혐오/욕설/저작권/기타)와 함께 신고합니다. 기타 사유는 상세 내용이 필수입니다. 본인이 작성한 댓글, 이미 신고한 댓글은 신고할 수 없습니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 댓글 신고
 */
export const reportComment = async (
  commentId: number,
  createReportRequest: CreateReportRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseReportResponse> => {
  return customFetch<DataResponseReportResponse>(getReportCommentUrl(commentId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReportRequest),
  })
}
