/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */
import type {
  CreateOcrResultBody,
  DataResponseOcrRecognize,
  DataResponsePageNumbers,
  DataResponsePassagesByPage,
  DataResponseSimilarCandidates,
  GetPageNumbersParams,
  SimilarCheck,
} from '../models'

import { customFetch } from '../../customFetch.api'

export const getCheckSimilarPassagesUrl = () => {
  return `/api/passages/similar-check`
}

/**
 * 저장 전 같은 도서의 인접 페이지(±1)에서 정규화 해시가 같은 대목 후보를 조회합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 유사 문장 후보 조회
 */
export const checkSimilarPassages = async (
  similarCheck: SimilarCheck,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseSimilarCandidates> => {
  return customFetch<DataResponseSimilarCandidates>(getCheckSimilarPassagesUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(similarCheck),
  })
}

export const getCreateOcrResultUrl = () => {
  return `/api/passages/ocr`
}

/**
 * 도서의 특정 페이지 이미지를 업로드하여 텍스트를 추출(인식)합니다.
 * @summary 이미지 OCR 텍스트 추출
 */
export const createOcrResult = async (
  createOcrResultBody?: CreateOcrResultBody,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseOcrRecognize> => {
  const formData = new FormData()
  if (createOcrResultBody?.image !== undefined) {
    formData.append(`image`, createOcrResultBody.image)
  }

  return customFetch<DataResponseOcrRecognize>(getCreateOcrResultUrl(), {
    ...options,
    method: 'POST',
    body: formData,
  })
}

export const getGetPageNumbersUrl = (bookId: number, params?: GetPageNumbersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/${bookId}/passages?${stringifiedParams}`
    : `/api/books/${bookId}/passages`
}

/**
 * 도서에서 발췌된 페이지 번호를 오름차순으로 조회합니다. 스포일러 대목이 있는 페이지도 이 목록에 포함됩니다(스포일러 블러 처리는 프론트 담당, isSpoiler 플래그 기반). 인증은 선택입니다(soft auth) — 헤더가 없어도 조회됩니다.
 * @summary 대목 페이지 목록 조회
 */
export const getPageNumbers = async (
  bookId: number,
  params?: GetPageNumbersParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponsePageNumbers> => {
  return customFetch<DataResponsePageNumbers>(getGetPageNumbersUrl(bookId, params), {
    ...options,
    method: 'GET',
  })
}

export const getGetPassagesByPageUrl = (bookId: number, page: number) => {
  return `/api/books/${bookId}/pages/${page}/passages`
}

/**
 * 같은 페이지에 여러 대목이 있으면 모두 반환합니다(대목 전환). 각 대목에는 좋아요 많은 순 최대 3개, 겹치지 않는 꾸밈만 병합되어 포함됩니다. 스포일러로 표기된 대목(isSpoiler=true)도 quotedText/decorations를 그대로 내려줍니다 — 블러 처리 후 [버튼]을 누르면 즉시 확인 가능해야 하므로, 블러/확인 전환은 서버 왕복 없이 프론트에서 isSpoiler 플래그로 처리합니다.
 * @summary 특정 페이지의 대목 + 꾸밈 병합 결과 조회
 */
export const getPassagesByPage = async (
  bookId: number,
  page: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponsePassagesByPage> => {
  return customFetch<DataResponsePassagesByPage>(getGetPassagesByPageUrl(bookId, page), {
    ...options,
    method: 'GET',
  })
}
