/**
 * Generated by orval — do not edit manually.
 */
import type { DataResponseBlockedUserListResponse } from '../models/dataResponseBlockedUserListResponse'

import type { DataResponseVoid } from '../models/dataResponseVoid'

import type { GetBlockedUsersParams } from '../models/getBlockedUsersParams'

import { customFetch } from '../../customFetch.api'

export const getBlockUrl = (userId: number) => {
  return `/api/users/${userId}/block`
}

/**
 * 해당 사용자를 차단합니다. 차단하면 이후 흔적 목록에서 차단한 사용자의 흔적이 보이지 않습니다. 본인은 차단할 수 없습니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 사용자 차단
 */
export const block = async (
  userId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getBlockUrl(userId), {
    ...options,
    method: 'POST',
  })
}

export const getUnblockUrl = (userId: number) => {
  return `/api/users/${userId}/block`
}

/**
 * 차단했던 사용자를 차단 해제합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 사용자 차단 해제
 */
export const unblock = async (
  userId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getUnblockUrl(userId), {
    ...options,
    method: 'DELETE',
  })
}

export const getGetBlockedUsersUrl = (params?: GetBlockedUsersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/users/me/blocks?${stringifiedParams}`
    : `/api/users/me/blocks`
}

/**
 * 내가 차단한 사용자 목록을 최신순으로 조회합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 차단 목록 조회
 */
export const getBlockedUsers = async (
  params?: GetBlockedUsersParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBlockedUserListResponse> => {
  return customFetch<DataResponseBlockedUserListResponse>(getGetBlockedUsersUrl(params), {
    ...options,
    method: 'GET',
  })
}
