/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */
import type {
  CreateOpinionRequest,
  DataResponseOpinionDetailResponse,
  DataResponseOpinionLikeResponse,
  DataResponseOpinionListResponse,
  DataResponseOpinionResponse,
  DataResponseVoid,
  GetOpinionsParams,
  UpdateOpinionRequest,
} from '../models'

import { customFetch } from '../../customFetch.api'

export const getCreateOpinionUrl = () => {
  return `/api/opinions`
}

/**
 * Passage(신규 생성 또는 기존 병합) + Opinion + Decoration을 원자적으로 생성합니다. passageId가 없으면 새 Passage를 만들고, 있으면 해당 Passage에 병합합니다(Q-06). OCR 입력은 별도 플로우이며 이 API는 직접 입력만 지원합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 흔적 작성 (직접 입력)
 */
export const createOpinion = async (
  createOpinionRequest: CreateOpinionRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseOpinionResponse> => {
  return customFetch<DataResponseOpinionResponse>(getCreateOpinionUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOpinionRequest),
  })
}

export const getToggleOpinionLikeUrl = (opinionId: number) => {
  return `/api/opinions/${opinionId}/like`
}

/**
 * 좋아요를 누르지 않은 상태면 좋아요를 남기고, 이미 눌렀다면 취소합니다. X-Debug-User-Id 헤더로 인증합니다(임시 스탠드인).
 * @summary 흔적 좋아요 토글
 */
export const toggleOpinionLike = async (
  opinionId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseOpinionLikeResponse> => {
  return customFetch<DataResponseOpinionLikeResponse>(getToggleOpinionLikeUrl(opinionId), {
    ...options,
    method: 'POST',
  })
}

export const getGetOpinionUrl = (opinionId: number) => {
  return `/api/opinions/${opinionId}`
}

/**
 * 흔적 작성자가 기록한 꾸밈을 그대로 확인합니다(병합된 결과가 아님).
 * @summary 흔적 상세 조회
 */
export const getOpinion = async (
  opinionId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseOpinionDetailResponse> => {
  return customFetch<DataResponseOpinionDetailResponse>(getGetOpinionUrl(opinionId), {
    ...options,
    method: 'GET',
  })
}

export const getRemoveOpinionUrl = (opinionId: number) => {
  return `/api/opinions/${opinionId}`
}

/**
 * 본인이 작성한 흔적을 소프트 삭제합니다.
 * @summary 흔적 삭제
 */
export const removeOpinion = async (
  opinionId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getRemoveOpinionUrl(opinionId), {
    ...options,
    method: 'DELETE',
  })
}

export const getModifyOpinionUrl = (opinionId: number) => {
  return `/api/opinions/${opinionId}`
}

/**
 * 본인이 작성한 흔적의 내용을 수정합니다. 꾸밈은 생성 시점에 고정되며 수정 대상이 아닙니다.
 * @summary 흔적 수정
 */
export const modifyOpinion = async (
  opinionId: number,
  updateOpinionRequest: UpdateOpinionRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseOpinionDetailResponse> => {
  return customFetch<DataResponseOpinionDetailResponse>(getModifyOpinionUrl(opinionId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateOpinionRequest),
  })
}

export const getGetOpinionsUrl = (passageId: number, params?: GetOpinionsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/passages/${passageId}/opinions?${stringifiedParams}`
    : `/api/passages/${passageId}/opinions`
}

/**
 * 특정 대목에 남겨진 흔적을 정렬 기준(최신순 기본/좋아요순)으로 조회합니다.
 * @summary 흔적 목록 조회
 */
export const getOpinions = async (
  passageId: number,
  params?: GetOpinionsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseOpinionListResponse> => {
  return customFetch<DataResponseOpinionListResponse>(getGetOpinionsUrl(passageId, params), {
    ...options,
    method: 'GET',
  })
}
