/**
 * Generated by orval — do not edit manually.
 */
import type { DataResponseNoticeListResponse } from '../models/dataResponseNoticeListResponse'

import type { DataResponseNoticeResponse } from '../models/dataResponseNoticeResponse'

import type { GetNoticesParams } from '../models/getNoticesParams'

import { customFetch } from '../../customFetch.api'

export const getGetNoticesUrl = (params?: GetNoticesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/api/notices?${stringifiedParams}` : `/api/notices`
}

/**
 * 공지사항을 최신순으로 조회합니다.
 * @summary 공지사항 목록 조회
 */
export const getNotices = async (
  params?: GetNoticesParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseNoticeListResponse> => {
  return customFetch<DataResponseNoticeListResponse>(getGetNoticesUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetNoticeUrl = (noticeId: number) => {
  return `/api/notices/${noticeId}`
}

/**
 * 공지사항 하나를 상세 조회합니다.
 * @summary 공지사항 상세 조회
 */
export const getNotice = async (
  noticeId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseNoticeResponse> => {
  return customFetch<DataResponseNoticeResponse>(getGetNoticeUrl(noticeId), {
    ...options,
    method: 'GET',
  })
}
