/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Pallang API Document
 * Pallang(팔랑) 프로젝트 API 명세서
 * OpenAPI spec version: 0.0.1
 */
import type {
  DataResponseNoticeListResponse,
  DataResponseNoticeResponse,
  GetNoticesParams,
} from '../models'

import { customFetch } from '../../customFetch.api'

export const getGetNoticesUrl = (params?: GetNoticesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/api/notices?${stringifiedParams}` : `/api/notices`
}

/**
 * 공지사항을 최신순으로 조회합니다.
 * @summary 공지사항 목록 조회
 */
export const getNotices = async (
  params?: GetNoticesParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseNoticeListResponse> => {
  return customFetch<DataResponseNoticeListResponse>(getGetNoticesUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetNoticeUrl = (noticeId: number) => {
  return `/api/notices/${noticeId}`
}

/**
 * 공지사항 하나를 상세 조회합니다.
 * @summary 공지사항 상세 조회
 */
export const getNotice = async (
  noticeId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseNoticeResponse> => {
  return customFetch<DataResponseNoticeResponse>(getGetNoticeUrl(noticeId), {
    ...options,
    method: 'GET',
  })
}
