/**
 * Generated by orval — do not edit manually.
 */
import type { CreateBookRequest } from '../models/createBookRequest'

import type { DataResponseBookActivityListResponse } from '../models/dataResponseBookActivityListResponse'

import type { DataResponseBookCarouselListResponse } from '../models/dataResponseBookCarouselListResponse'

import type { DataResponseBookListResponse } from '../models/dataResponseBookListResponse'

import type { DataResponseBookResponse } from '../models/dataResponseBookResponse'

import type { DataResponseBookSearchListResponse } from '../models/dataResponseBookSearchListResponse'

import type { DataResponseExternalBookListResponse } from '../models/dataResponseExternalBookListResponse'

import type { GetHomeCarouselBooksParams } from '../models/getHomeCarouselBooksParams'

import type { GetPopularBooksParams } from '../models/getPopularBooksParams'

import type { GetRecentBooksParams } from '../models/getRecentBooksParams'

import type { SearchExternalBooksParams } from '../models/searchExternalBooksParams'

import type { SearchInternalBooksParams } from '../models/searchInternalBooksParams'

import { customFetch } from '../../customFetch.api'

export const getCreateBookUrl = () => {
  return `/api/books`
}

/**
 * 검색 결과에 없는 도서를 직접 등록합니다. 인증 불필요.
 * @summary 도서 직접 등록
 */
export const createBook = async (
  createBookRequest: CreateBookRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookResponse> => {
  return customFetch<DataResponseBookResponse>(getCreateBookUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBookRequest),
  })
}

export const getGetHomeCarouselBooksUrl = (params?: GetHomeCarouselBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/api/home/books?${stringifiedParams}` : `/api/home/books`
}

/**
 * 흔적이 남은 도서를 대목/흔적 수와 함께 조회합니다. offset을 생략하면 전체 목록 중 정가운데 책들을 기준으로 조회하며, 좌우 스크롤 시에는 응답으로 받은 pageInfo를 참고해 offset - size(이전) 또는 offset + size(다음)로 다시 요청하면 됩니다.
 * @summary 홈 캐러셀 도서 목록
 */
export const getHomeCarouselBooks = async (
  params?: GetHomeCarouselBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookCarouselListResponse> => {
  return customFetch<DataResponseBookCarouselListResponse>(getGetHomeCarouselBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getSearchExternalBooksUrl = (params: SearchExternalBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/search?${stringifiedParams}`
    : `/api/books/search`
}

/**
 * 알라딘 Open API로 도서를 검색합니다. 응답 속도를 위해 pageCount는 내려주지 않으며, 등록 시 사용자가 직접 입력합니다.
 * @summary 도서 외부 검색
 */
export const searchExternalBooks = async (
  params: SearchExternalBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseExternalBookListResponse> => {
  return customFetch<DataResponseExternalBookListResponse>(getSearchExternalBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetRecentBooksUrl = (params?: GetRecentBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/recent?${stringifiedParams}`
    : `/api/books/recent`
}

/**
 * 현재 로그인한 사용자가 최근에 대목을 남긴 도서 목록입니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 내가 최근에 남긴 도서 목록
 */
export const getRecentBooks = async (
  params?: GetRecentBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookListResponse> => {
  return customFetch<DataResponseBookListResponse>(getGetRecentBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetPopularBooksUrl = (params?: GetPopularBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/popular?${stringifiedParams}`
    : `/api/books/popular`
}

/**
 * 서비스 전체에서 흔적(Opinion)이 많은 순으로 도서를 조회합니다.
 * @summary 흔적 많은 도서 목록
 */
export const getPopularBooks = async (
  params?: GetPopularBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookActivityListResponse> => {
  return customFetch<DataResponseBookActivityListResponse>(getGetPopularBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getSearchInternalBooksUrl = (params: SearchInternalBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/internal-search?${stringifiedParams}`
    : `/api/books/internal-search`
}

/**
 * 서비스 DB에 이미 등록된 도서를 제목으로 검색하며, 도서별 대목/흔적 수를 함께 반환합니다. 제목과 검색어의 띄어쓰기 차이는 무시하고 매칭합니다. keyword에 빈 문자열을 넘기면 전체 목록을 반환합니다.
 * @summary 도서 내부 검색
 */
export const searchInternalBooks = async (
  params: SearchInternalBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookSearchListResponse> => {
  return customFetch<DataResponseBookSearchListResponse>(getSearchInternalBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}
