/**
 * Generated by orval — do not edit manually.
 */
import type { CreateBookBody } from '../models/createBookBody'

import type { DataResponseBookActivityListResponse } from '../models/dataResponseBookActivityListResponse'

import type { DataResponseBookDetailResponse } from '../models/dataResponseBookDetailResponse'

import type { DataResponseBookListResponse } from '../models/dataResponseBookListResponse'

import type { DataResponseBookResponse } from '../models/dataResponseBookResponse'

import type { DataResponseBookSearchListResponse } from '../models/dataResponseBookSearchListResponse'

import type { GetMyLibraryBooksParams } from '../models/getMyLibraryBooksParams'

import type { GetPopularBooksParams } from '../models/getPopularBooksParams'

import type { GetRecentBooksParams } from '../models/getRecentBooksParams'

import type { SearchBooksParams } from '../models/searchBooksParams'

import type { SearchInternalBooksParams } from '../models/searchInternalBooksParams'

import { customFetch } from '../../customFetch.api'

export const getCreateBookUrl = () => {
  return `/api/books`
}

/**
 * 검색 결과에 없는 도서를 직접 등록합니다. 인증 불필요. multipart/form-data로 요청하며, coverImage는 선택 항목입니다.
 * @summary 도서 직접 등록
 */
export const createBook = async (
  createBookBody?: CreateBookBody,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookResponse> => {
  const formData = new FormData()
  if (createBookBody?.book !== undefined) {
    formData.append(`book`, JSON.stringify(createBookBody.book))
  }
  if (createBookBody?.coverImage !== undefined) {
    formData.append(`coverImage`, createBookBody.coverImage)
  }

  return customFetch<DataResponseBookResponse>(getCreateBookUrl(), {
    ...options,
    method: 'POST',
    body: formData,
  })
}

export const getGetBookDetailUrl = (bookId: number) => {
  return `/api/books/${bookId}`
}

/**
 * bookId로 도서 메타(제목/저자/출판사/표지/대목·흔적 수)를 조회합니다. 인증 불필요. Authorization: Bearer {accessToken} 헤더를 보내면 myStatus/myCurrentPage(로그인 사용자의 읽기상태/현재페이지)도 함께 내려주며, 헤더가 없거나 로그인 사용자가 이 도서에 읽기상태를 남기지 않았으면 myStatus/myCurrentPage 필드 자체가 응답에서 제외됩니다(null이 아니라 키 자체가 없음).
 * @summary 도서 단건 조회
 */
export const getBookDetail = async (
  bookId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookDetailResponse> => {
  return customFetch<DataResponseBookDetailResponse>(getGetBookDetailUrl(bookId), {
    ...options,
    method: 'GET',
  })
}

export const getSearchBooksUrl = (params: SearchBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/search?${stringifiedParams}`
    : `/api/books/search`
}

/**
 * 알라딘 Open API 검색 결과와 서비스 DB에 등록된 도서(수동 등록 포함)를 함께 검색합니다. 이미 등록된 도서는 bookId/source가 채워져 내려가고, 알라딘에만 있고 아직 등록되지 않은 도서는 bookId/source가 null이며 pageCount/passageCount/opinionCount는 0입니다. 같은 책이 알라딘과 DB 양쪽에 모두 있으면(ISBN 동일) 이미 등록된 DB 쪽만 남기고 알라딘 쪽은 페이지와 무관하게 항상 제외합니다(ISBN이 없는 알라딘 결과는 비교할 수 없어 그대로 둡니다). DB 도서(흔적 많은 순 정렬)와 알라딘 결과를 하나로 이어붙인 목록으로 취급해 페이지네이션하므로, DB 매칭이 페이지 크기보다 많아도 페이지를 넘기면 빠짐없이 노출되며 같은 도서가 중복 노출되지 않습니다(DB 매칭을 다 지나간 뒤부터 알라딘 결과가 이어서 채워집니다). totalElements는 DB 전체 매칭 수 + 알라딘 전체 매칭 수입니다. 단, 알라딘은 키워드당 최대 200건까지만 결과를 제공하므로, 알라딘 쪽 매칭이 200건을 넘는 키워드는 200건을 넘어가는 페이지부터 알라딘 항목이 더 채워지지 않을 수 있습니다. 타이핑 중 자동완성 미리보기 용도로도 재사용되므로, keyword가 공백 제거 후 2글자 미만이면 알라딘을 호출하지 않고 빈 목록을 반환합니다. 알라딘 쪽 결과는 동일 keyword로 최대 12시간 캐싱되어 즉시 반영되지 않을 수 있습니다.
 * @summary 도서 검색
 */
export const searchBooks = async (
  params: SearchBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookSearchListResponse> => {
  return customFetch<DataResponseBookSearchListResponse>(getSearchBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetRecentBooksUrl = (params?: GetRecentBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/recent?${stringifiedParams}`
    : `/api/books/recent`
}

/**
 * 현재 로그인한 사용자가 최근에 대목을 남긴 도서 목록입니다. 홈 화면 검색에서 사용할 수 있도록 keyword로 제목을 필터링할 수 있으며, 생략하거나 빈 문자열이면 전체 목록을 반환합니다. 제목과 검색어의 띄어쓰기 차이는 무시하고 매칭합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 내가 최근에 남긴 도서 목록
 */
export const getRecentBooks = async (
  params?: GetRecentBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookListResponse> => {
  return customFetch<DataResponseBookListResponse>(getGetRecentBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetPopularBooksUrl = (params?: GetPopularBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/popular?${stringifiedParams}`
    : `/api/books/popular`
}

/**
 * 서비스 전체에서 흔적(Opinion)이 많은 순으로 도서를 조회합니다.
 * @summary 흔적 많은 도서 목록
 */
export const getPopularBooks = async (
  params?: GetPopularBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookActivityListResponse> => {
  return customFetch<DataResponseBookActivityListResponse>(getGetPopularBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetMyLibraryBooksUrl = (params?: GetMyLibraryBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/my-library?${stringifiedParams}`
    : `/api/books/my-library`
}

/**
 * 현재 로그인한 사용자가 흔적을 남긴 도서만 대상으로, 대목/흔적 수와 함께 조회합니다. 가장 최근에 흔적을 남긴 도서부터 내림차순으로 정렬됩니다. opinionCountScope로 흔적 수 집계 기준을 선택할 수 있습니다: ALL(기본값, 도서 전체 흔적 수 - 홈 화면 노출용) 또는 MINE(로그인 사용자 본인이 남긴 흔적 수 - 마이페이지 노출용). 인증 불필요. Authorization: Bearer {accessToken} 헤더가 없으면(비로그인) 샘플 도서 1건을 고정 응답으로 반환합니다.
 * @summary 내 서재 도서 목록
 */
export const getMyLibraryBooks = async (
  params?: GetMyLibraryBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookActivityListResponse> => {
  return customFetch<DataResponseBookActivityListResponse>(getGetMyLibraryBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getSearchInternalBooksUrl = (params: SearchInternalBooksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/books/internal-search?${stringifiedParams}`
    : `/api/books/internal-search`
}

/**
 * 서비스 DB에 등록된 도서 전체를 흔적(Opinion) 유무와 무관하게 제목으로 검색하며, 도서별 대목/흔적 수를 함께 반환합니다(흔적이 없으면 0). 제목과 검색어의 띄어쓰기 차이는 무시하고 매칭합니다. keyword에 빈 문자열을 넘기면 전체 목록을 반환합니다.
 * @summary 도서 내부 검색
 */
export const searchInternalBooks = async (
  params: SearchInternalBooksParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseBookSearchListResponse> => {
  return customFetch<DataResponseBookSearchListResponse>(getSearchInternalBooksUrl(params), {
    ...options,
    method: 'GET',
  })
}
