/**
 * Generated by orval — do not edit manually.
 */
import type { CreateCommentRequest } from '../models/createCommentRequest'

import type { DataResponseCommentListResponse } from '../models/dataResponseCommentListResponse'

import type { DataResponseCommentResponse } from '../models/dataResponseCommentResponse'

import type { DataResponseRootCommentListResponse } from '../models/dataResponseRootCommentListResponse'

import type { DataResponseVoid } from '../models/dataResponseVoid'

import type { GetCommentsParams } from '../models/getCommentsParams'

import type { GetRepliesParams } from '../models/getRepliesParams'

import type { UpdateCommentRequest } from '../models/updateCommentRequest'

import { customFetch } from '../../customFetch.api'

export const getGetCommentsUrl = (opinionId: number, params?: GetCommentsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/opinions/${opinionId}/comments?${stringifiedParams}`
    : `/api/opinions/${opinionId}/comments`
}

/**
 * 흔적에 달린 원댓글과 답글을 조회합니다. 원댓글은 page/size로 페이지네이션되며, 각 원댓글에는 답글이 최대 5개까지 미리보기로 포함됩니다. 5개를 초과하면 hasMoreReplies=true이며, 나머지는 GET /api/comments/{commentId}/replies로 조회합니다.
 * @summary 댓글 목록 조회
 */
export const getComments = async (
  opinionId: number,
  params?: GetCommentsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseRootCommentListResponse> => {
  return customFetch<DataResponseRootCommentListResponse>(getGetCommentsUrl(opinionId, params), {
    ...options,
    method: 'GET',
  })
}

export const getCreateCommentUrl = (opinionId: number) => {
  return `/api/opinions/${opinionId}/comments`
}

/**
 * 흔적에 댓글 또는 답글을 작성합니다. parentCommentId가 없으면 원댓글, 있으면 답글로 생성됩니다. 답글에는 다시 답글을 남길 수 없습니다(1-depth). 삭제된 댓글을 부모로 답글을 작성할 수 없습니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 댓글/답글 작성
 */
export const createComment = async (
  opinionId: number,
  createCommentRequest: CreateCommentRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseCommentResponse> => {
  return customFetch<DataResponseCommentResponse>(getCreateCommentUrl(opinionId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCommentRequest),
  })
}

export const getRemoveCommentUrl = (commentId: number) => {
  return `/api/comments/${commentId}`
}

/**
 * 본인이 작성한 댓글/답글을 소프트 삭제합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 댓글/답글 삭제
 */
export const removeComment = async (
  commentId: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseVoid> => {
  return customFetch<DataResponseVoid>(getRemoveCommentUrl(commentId), {
    ...options,
    method: 'DELETE',
  })
}

export const getModifyCommentUrl = (commentId: number) => {
  return `/api/comments/${commentId}`
}

/**
 * 본인이 작성한 댓글/답글의 내용을 수정합니다. Authorization: Bearer {accessToken} 헤더로 인증합니다.
 * @summary 댓글/답글 수정
 */
export const modifyComment = async (
  commentId: number,
  updateCommentRequest: UpdateCommentRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseCommentResponse> => {
  return customFetch<DataResponseCommentResponse>(getModifyCommentUrl(commentId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCommentRequest),
  })
}

export const getGetRepliesUrl = (commentId: number, params?: GetRepliesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/comments/${commentId}/replies?${stringifiedParams}`
    : `/api/comments/${commentId}/replies`
}

/**
 * 특정 원댓글에 달린 답글을 page/size로 페이지네이션 조회합니다.
 * @summary 답글 더보기
 */
export const getReplies = async (
  commentId: number,
  params?: GetRepliesParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<DataResponseCommentListResponse> => {
  return customFetch<DataResponseCommentListResponse>(getGetRepliesUrl(commentId, params), {
    ...options,
    method: 'GET',
  })
}
